# Outline

1. Load Data
2. Clean Data
3. Create TFIDF Vectors

In [3]:
# Imports
import pandas as pd
import numpy as np
import seaborn as sb
import textstat

from utils import clean_text
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/dbingham/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

## 1. Load the Dataset

In [21]:
# Load the dataset
dataset = pd.read_csv('data/processed_combined_data.csv', usecols=[0,1,2,3,4,5,6,7,8,9])

# Work with a sample for prototyping
dataset = dataset.sample(n=5000, random_state=24)
dataset.head()

/var/folders/y7/989__f2x3hn66yzt31xjhpxm0000gn/T/ipykernel_72109/3986870448.py:2: DtypeWarning: Columns (0,1,2,4,5,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv('data/processed_combined_data.csv', usecols=[0,1,2,3,4,5,6,7,8,9])

,Unnamed: 0,label,author,text,date,dataset,type,title,subject,extracted_source
9745,9745,2,Patty Judge,"When a bill is sent to the governors office, t...",6/1/16,1,statement,NaN,NaN,NaN
60584,61193,0,NaN,Says Greg Abbott converted over 1 million in f...,NaN,2,statement,NaN,"crime,criminal-justice,elections,legal-issues",NaN
113662,114469,0,NaN,Donald Trump has absolutely no evidence that P...,NaN,4,article,WATCH: Former Director Of National Intelligen...,NaN,NaN
53155,53145,0,NaN,source infowars vote fraud expert bev harris e...,NaN,4,NaN,why hillary clintons campaign is collapsing t...,NaN,NaN
77428,78257,4,NaN,HARARE Reuters - Zimbabwe President Robert Mug...,NaN,3,article,Zimbabwe's Mugabe speech was meant to sanitize...,worldnews,Reuters

## 2. Clean Data

In [22]:
# Drop rows where 'text' is missing
dataset_tokenized = dataset[dataset['text'].notnull()].copy()

# Optional: Preprocess text (e.g., lowercasing, remove numbers, punctuation, extra whitespace, and tokenize)
dataset_tokenized['text_tokenized'] = dataset_tokenized['text'].apply(clean_text)
dataset_tokenized['cleaned_text'] = dataset_tokenized['text_tokenized'].apply(lambda x: ' '.join(x))

In [17]:
dataset_tokenized.head()

,label,author,text,date,dataset,type,title,subject,extracted_source,text_tokenized,cleaned_text
Unnamed: 0,,,,,,,,,,,
9745,2,Patty Judge,"When a bill is sent to the governors office, t...",6/1/16,1,statement,NaN,NaN,NaN,"[when, a, bill, is, sent, to, the, governors, ...",when a bill is sent to the governors office th...
61193,0,NaN,Says Greg Abbott converted over 1 million in f...,NaN,2,statement,NaN,"crime,criminal-justice,elections,legal-issues",NaN,"[says, greg, abbott, converted, over, million,...",says greg abbott converted over million in fed...
114469,0,NaN,Donald Trump has absolutely no evidence that P...,NaN,4,article,WATCH: Former Director Of National Intelligen...,NaN,NaN,"[donald, trump, has, absolutely, no, evidence,...",donald trump has absolutely no evidence that p...
53145,0,NaN,source infowars vote fraud expert bev harris e...,NaN,4,NaN,why hillary clintons campaign is collapsing t...,NaN,NaN,"[source, infowars, vote, fraud, expert, bev, h...",source infowars vote fraud expert bev harris e...
78257,4,NaN,HARARE Reuters - Zimbabwe President Robert Mug...,NaN,3,article,Zimbabwe's Mugabe speech was meant to sanitize...,worldnews,Reuters,"[harare, reuters, zimbabwe, president, robert,...",harare reuters zimbabwe president robert mugab...

In [18]:
dataset_tokenized['label'].unique()

array([2, 0, '0', 4, '4', 1, 3, '2', '1', '3',
       ' while criticizing their conservative counterparts.National Committee for Voting Integrity This group opposes  the implementation of proof of citizenship and photo identification requirements for eligible electors in American elections as the means of assuring election integrity. National Council for Research on Women This group supports big government',
       ' like the fraudulent story published in The Post'], dtype=object)

## 3. Create TF-IDF Vectors

In [ ]:
#########
# CREATE - TFIDF vectors
#########

# Initialize the TF-Idataset Vectorizer with a maximum number of features and English stopwords removal
tfidf_vectorizer = TfidfVectorizer(max_features=1000, stop_words='english')

# Fit and transform the cleaned text into a TF-Idataset feature matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(dataset_tokenized['cleaned_text'])

# Convert the TF-Idataset matrix to a DataFrame for inspection or further processing
tfidf_dataset = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

# Optionally, add the label column for reference in further analysis
tfidf_dataset['label'] = dataset_tokenized['label'].values

# Bring back some of the original columns for reference
tfidf_df = pd.concat([dataset_tokenized[['Unnamed: 0', 'label', 'text', 'cleaned_text']].reset_index(drop=True), tfidf_dataset], axis=1)

# Display the first few rows of the TF-Idataset features
print(tfidf_df.head())

tfidf_df.describe()

   able  absolutely  access  according  account  accused       act    action  \
0   0.0    0.000000     0.0        0.0      0.0      0.0  0.000000  0.000000
1   0.0    0.000000     0.0        0.0      0.0      0.0  0.000000  0.000000
2   0.0    0.080098     0.0        0.0      0.0      0.0  0.000000  0.000000
3   0.0    0.000000     0.0        0.0      0.0      0.0  0.000000  0.000000
4   0.0    0.000000     0.0        0.0      0.0      0.0  0.169135  0.177872

   actions  actually  ...  wrong  wrote   xi  year  yearold  years  yes  york  \
0      0.0       0.0  ...    0.0    0.0  0.0   0.0      0.0    0.0  0.0   0.0
1      0.0       0.0  ...    0.0    0.0  0.0   0.0      0.0    0.0  0.0   0.0
2      0.0       0.0  ...    0.0    0.0  0.0   0.0      0.0    0.0  0.0   0.0
3      0.0       0.0  ...    0.0    0.0  0.0   0.0      0.0    0.0  0.0   0.0
4      0.0       0.0  ...    0.0    0.0  0.0   0.0      0.0    0.0  0.0   0.0

   young  label
0    0.0      2
1    0.0      0
2    0.0      0
3    0.0      0
4    0.0      4

[5 rows x 1001 columns]

,able,absolutely,access,according,account,accused,act,action,actions,actually,...,worth,wrong,wrote,xi,year,yearold,years,yes,york,young
count,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,...,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000,4992.000000
mean,0.004883,0.002576,0.004000,0.009849,0.003115,0.004551,0.006571,0.004633,0.002942,0.007002,...,0.002647,0.003417,0.004920,0.002556,0.015742,0.004480,0.014659,0.002938,0.008509,0.003938
std,0.028327,0.016044,0.026422,0.030350,0.024399,0.021829,0.034339,0.022920,0.019326,0.035192,...,0.021939,0.024019,0.024782,0.030326,0.046269,0.025458,0.045106,0.022643,0.036742,0.024802
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,0.874997,0.208588,0.616692,0.333686,0.586101,0.410037,0.686885,0.399429,0.434749,0.710404,...,0.489670,0.575507,0.471202,0.734105,0.782640,0.689963,0.598714,0.696008,0.627755,0.561072

## 4. Flesch Reading Ease Score

In [25]:
# Compute the Flesch Reading Ease score for each document
dataset_flesch = dataset_tokenized.copy()
dataset_flesch['flesch_reading_ease'] = dataset_flesch['text'].apply(textstat.flesch_reading_ease)

# (Optional) Inspect the computed scores
print(dataset_flesch[['cleaned_text', 'flesch_reading_ease']].head())

                                             cleaned_text  flesch_reading_ease
9745    when a bill is sent to the governors office th...                74.90
60584   says greg abbott converted over million in fed...                 9.90
113662  donald trump has absolutely no evidence that p...                44.64
53155   source infowars vote fraud expert bev harris e...               -64.54
77428   harare reuters zimbabwe president robert mugab...                57.10

## Combine and Output csv

In [26]:
final_df = tfidf_df.copy()

# Add the Flesch Reading Ease scores to the TF-Idataset DataFrame
final_df['flesch_reading_ease'] = dataset_flesch['flesch_reading_ease'].values

# Save the final dataset to a CSV file
final_df.to_csv('data/final_dataset.csv', index=False)