# Outline

1. Load Data
2. Clean Data
3. Create TFIDF Vectors

In [ ]:
# Imports
import pandas as pd
import numpy as np
import seaborn as sb
import textstat

from utils import clean_text
from sklearn.feature_extraction.text import TfidfVectorizer

## 1. Load the Dataset

In [ ]:
# Load the dataset
dataset = pd.read_csv('data/processed_combined_data.csv', usecols=[0,1,2,3,4,5,6,7,8,9], index_col=0)

dataset.head()

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/dbingham/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
/var/folders/y7/989__f2x3hn66yzt31xjhpxm0000gn/T/ipykernel_53215/3850943431.py:10: DtypeWarning: Columns (0,1,2,4,5,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv('data/processed_combined_data.csv', usecols=[0,1,2,3,4,5,6,7,8,9], index_col=0)

,label,author,text,date,dataset,type,title,subject,extracted_source
Unnamed: 0,,,,,,,,,
0,4,Barack Obama,John McCain opposed bankruptcy protections for...,6/11/08,1,statement,NaN,NaN,NaN
1,0,Matt Gaetz,Bennie Thompson actively cheer-led riots in th...,6/7/22,1,statement,NaN,NaN,NaN
2,3,Kelly Ayotte,Says Maggie Hassan was out of state on 30 days...,5/18/16,1,statement,NaN,NaN,NaN
3,0,Bloggers,"BUSTED CDC Inflated COVID Numbers, Accused of ...",2/1/21,1,statement,NaN,NaN,NaN
4,2,Bobby Jindal,Im the only Republican candidate that has actu...,8/30/15,1,statement,NaN,NaN,NaN

## 2. Clean Data

In [ ]:
# Drop rows where 'text' is missing
dataset_tokenized = dataset[dataset['text'].notnull()].copy()

# Optional: Preprocess text (e.g., lowercasing, remove numbers, punctuation, extra whitespace, and tokenize)
dataset_tokenized['text_tokenized'] = dataset_tokenized['text'].apply(clean_text)
dataset_tokenized['cleaned_text'] = dataset_tokenized['text_tokenized'].apply(lambda x: ' '.join(x))

In [7]:
dataset_tokenized.head()

,label,author,text,date,dataset,type,title,subject,extracted_source,text_tokenized,cleaned_text
Unnamed: 0,,,,,,,,,,,
0,4,Barack Obama,John McCain opposed bankruptcy protections for...,6/11/08,1,statement,NaN,NaN,NaN,"[john, mccain, opposed, bankruptcy, protection...",john mccain opposed bankruptcy protections for...
1,0,Matt Gaetz,Bennie Thompson actively cheer-led riots in th...,6/7/22,1,statement,NaN,NaN,NaN,"[bennie, thompson, actively, cheerled, riots, ...",bennie thompson actively cheerled riots in the s
2,3,Kelly Ayotte,Says Maggie Hassan was out of state on 30 days...,5/18/16,1,statement,NaN,NaN,NaN,"[says, maggie, hassan, was, out, of, state, on...",says maggie hassan was out of state on days ov...
3,0,Bloggers,"BUSTED CDC Inflated COVID Numbers, Accused of ...",2/1/21,1,statement,NaN,NaN,NaN,"[busted, cdc, inflated, covid, numbers, accuse...",busted cdc inflated covid numbers accused of v...
4,2,Bobby Jindal,Im the only Republican candidate that has actu...,8/30/15,1,statement,NaN,NaN,NaN,"[im, the, only, republican, candidate, that, h...",im the only republican candidate that has actu...

## 3. Create TF-IDF Vectors

In [9]:
#########
# CREATE - TFIDF vectors
#########

# Initialize the TF-Idataset Vectorizer with a maximum number of features and English stopwords removal
tfidf_vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')

# Fit and transform the cleaned text into a TF-Idataset feature matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(dataset_tokenized['cleaned_text'])

# Convert the TF-Idataset matrix to a DataFrame for inspection or further processing
tfidf_dataset = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

# Optionally, add the label column for reference in further analysis
tfidf_dataset['label'] = dataset_tokenized['label'].values

# Display the first few rows of the TF-Idataset features
print(tfidf_dataset.head())

tfidf_dataset.describe()

   abandon  abandoned  abbas  abc  abdullah  abe  abedin  ability  able  \
0      0.0        0.0    0.0  0.0       0.0  0.0     0.0      0.0   0.0
1      0.0        0.0    0.0  0.0       0.0  0.0     0.0      0.0   0.0
2      0.0        0.0    0.0  0.0       0.0  0.0     0.0      0.0   0.0
3      0.0        0.0    0.0  0.0       0.0  0.0     0.0      0.0   0.0
4      0.0        0.0    0.0  0.0       0.0  0.0     0.0      0.0   0.0

   abortion  ...  youth  youtube  ypg  zealand  zero  zika  zimbabwe  zone  \
0       0.0  ...    0.0      0.0  0.0      0.0   0.0   0.0       0.0   0.0
1       0.0  ...    0.0      0.0  0.0      0.0   0.0   0.0       0.0   0.0
2       0.0  ...    0.0      0.0  0.0      0.0   0.0   0.0       0.0   0.0
3       0.0  ...    0.0      0.0  0.0      0.0   0.0   0.0       0.0   0.0
4       0.0  ...    0.0      0.0  0.0      0.0   0.0   0.0       0.0   0.0

   zones  zuma
0    0.0   0.0
1    0.0   0.0
2    0.0   0.0
3    0.0   0.0
4    0.0   0.0

[5 rows x 5000 columns]

,abandon,abandoned,abbas,abc,abdullah,abe,abedin,ability,able,abortion,...,youth,youtube,ypg,zealand,zero,zika,zimbabwe,zone,zones,zuma
count,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,...,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000,115935.000000
mean,0.000390,0.000432,0.000453,0.001376,0.000445,0.001111,0.000547,0.001590,0.003260,0.002582,...,0.000733,0.001144,0.000336,0.000724,0.001295,0.000709,0.000801,0.001240,0.000510,0.000631
std,0.005854,0.007465,0.011362,0.015640,0.009618,0.019422,0.012477,0.012375,0.016460,0.029942,...,0.012153,0.012023,0.009378,0.016112,0.016137,0.018877,0.015676,0.013693,0.010075,0.018313
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,0.268397,0.651680,0.654801,0.582632,0.609079,0.699853,0.696591,0.683912,0.481499,1.000000,...,0.791154,0.535386,0.674314,0.713670,0.817914,0.897669,0.775176,0.655472,0.614835,0.818915

## 4. Flesch Reading Ease Score

In [ ]:
# Compute the Flesch Reading Ease score for each document
dataset_flesch = dataset_tokenized.copy()
dataset_flesch['flesch_reading_ease'] = dataset_flesch['cleaned_text'].apply(textstat.flesch_reading_ease)

# (Optional) Inspect the computed scores
print(dataset_flesch[['text_clean', 'flesch_reading_ease']].head())

## Combine and Output csv

In [ ]:
final_df = tfidf_dataset.copy()

# Add the Flesch Reading Ease scores to the TF-Idataset DataFrame
final_df['flesch_reading_ease'] = dataset_flesch['flesch_reading_ease'].values

# Save the final dataset to a CSV file
final_df.to_csv('data/final_dataset.csv', index=False)